# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-28 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leasingforgotpassword', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('to_email', models.CharField(max_length=255)),
                ('from_email', models.CharField(max_length=255)),
                ('send_now', models.BooleanField(default=False)),
                ('reset_password', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reset_password', to='leasingforgotpassword.LeasingResetPassword')),
            ],
        ),
        migrations.CreateModel(
            name='EmailQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('to_email', models.CharField(max_length=255)),
                ('from_email', models.CharField(max_length=255)),
                ('send_now', models.BooleanField(default=False)),
                ('reset_password', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reset_password', to='leasingforgotpassword.LeasingResetPassword')),
            ],
        ),
    ]
