# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-01 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leasingauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('AUS', 'AUSTRALIA'), ('UK', 'UNITED KINGDOM'), ('US', 'UNITED STATES'), ('NZ', 'NEW ZEALAND'), ('CAN', 'CANADA')], default='AUS', max_length=3)),
                ('state', models.CharField(choices=[('NSW', 'NEW SOUTH WALES'), ('ACT', 'AUSTRALIAN CAPITAL TERITORY'), ('NT', 'NORTHERN TERITORY'), ('QLD', 'QUEENSLAND'), ('SA', 'SOUTH AUSTRALIA'), ('TAS', 'TASMANIA'), ('VIC', 'VICTORIA'), ('WA', 'WESTERN AUSTRALIA'), ('AL', 'ALABAMA'), ('AK', 'ALASKA'), ('AZ', 'ARIZONA'), ('AR', 'ARKANSAS'), ('CA', 'CALIFORNIA'), ('CO', 'COLORADO'), ('CT', 'CONNECTICUT'), ('DE', 'DELAWARE'), ('FL', 'FLORIDA'), ('GA', 'GEORGIA'), ('HI', 'HAWAII'), ('ID', 'IDAHO'), ('IL', 'ILLINOIS'), ('IN', 'INDIANA'), ('IA', 'IOWA'), ('KS', 'KANSAS'), ('KY', 'KENTUCKY'), ('LA', 'LOUISIANA'), ('ME', 'MAINE'), ('MD', 'MARYLAND'), ('MA', 'MASSACHUSETTS'), ('MI', 'MICHIGAN'), ('MN', 'MINNESOTA'), ('MS', 'MISSISSIPPI'), ('MO', 'MISSOURI'), ('MT', 'MONTANA'), ('NE', 'NEBRASKA'), ('NV', 'NEVADA'), ('NH', 'NEW HAMPSHIRE'), ('NJ', 'NEW JERSEY'), ('NM', 'NEW MEXICO'), ('NY', 'NEW YORK'), ('NC', 'NORTH CAROLINA'), ('ND', 'NORTH DAKOTA'), ('OH', 'OHIO'), ('OKLAHOMA', 'OKLAHOMA'), ('OR', 'OREGON'), ('PA', 'PENNSYLVANIA'), ('RI', 'RHODE ISLAND'), ('SC', 'SOUTH CAROLINA'), ('SD', 'SOUTH DAKOTA'), ('TN', 'TENNESSEE'), ('TX', 'TEXAS'), ('UT', 'UTAH'), ('VT', 'VERMONT'), ('VA', 'VIRGINIA'), ('WA', 'WASHINGTON'), ('WV', 'WEST VIRGINIA'), ('WI', 'WISCONSIN'), ('WY', 'WYOMING'), ('ENG', 'ENGLAND'), ('NIR', 'NORTHERN IRELAND'), ('SCO', 'SCOTLAND'), ('WAL', 'WALES'), ('NZ-AUK', 'AUCKLAND'), ('NZ-BOP', 'BAY OF PLENTY'), ('NZ-CAN', 'CANTERBURY'), ('NZ-GIS', 'GISBORNE'), ('NZ-HKB', "HAWKE'S BAY"), ('NZ-MBH', 'MARLBOROUGH'), ('NZ-MWT', 'ANAWATU-WANGANUI'), ('NZ-NSN', 'NELSON'), ('NZ-NTL', 'NORTH LAND'), ('NZ-OTA', 'OTAGO'), ('NZ-STL', 'SOUTH LAND'), ('NZ-TAS', 'TASMAN'), ('NZ-TKI', 'TARANAKI'), ('NZ-WKO', 'WAIKATO'), ('NZ-WGN', 'WELLINGTON'), ('NZ-WTC', 'WEST COAST'), ('NZ-CIT', 'CHATHAM ISLANDS TERRITORY'), ('AB', 'ALBERTA'), ('BC', 'BRITISH COLUMBIA'), ('MB', 'MANITOBA'), ('NB', 'NEW BRUNSWICK'), ('NL', 'NEWFOUNDLAND AND LABRADOR'), ('NT', 'NORTHWEST TERRITORIES'), ('NS', 'NOVA SCOTIA'), ('NU', 'NUNAVUT'), ('ON', 'ONTARIO'), ('PE', 'PRINCE EDWARD ISLAND'), ('QC', 'QUEBEC'), ('SK', 'SASKATCHEWAN'), ('YT', 'YUKON')], default='NSW', max_length=6)),
                ('representing', models.CharField(choices=[('TNT', 'TENANT'), ('LND', 'LANDLORD')], default='TNT', max_length=3)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_settings', to='leasingauth.LeasingClient')),
            ],
            options={
                'verbose_name_plural': 'Client Settings',
            },
        ),
        migrations.CreateModel(
            name='DocumentUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='client_documents/')),
                ('upload_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_uploads', to='leasingauth.LeasingClient')),
            ],
            options={
                'verbose_name_plural': 'Document Uploads',
            },
        ),
    ]
