# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-10 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leasingapi', '0002_legalposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalposition',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legal_positions', to='leasingapi.DocumentUpload'),
        ),
    ]
