# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-24 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leasingapi', '0005_auto_20190117_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalposition',
            name='setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_setting', to='leasingapi.ClientSetting'),
        ),
    ]
