# Generated by Django 2.1.5 on 2019-02-11 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leasingapi', '0007_auto_20190124_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalposition',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_positions', to='leasingapi.DocumentUpload'),
        ),
        migrations.AlterField(
            model_name='legalposition',
            name='export_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_result', to='leasingapi.ExportResult'),
        ),
        migrations.AlterField(
            model_name='legalposition',
            name='setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_setting', to='leasingapi.ClientSetting'),
        ),
    ]
