# Generated by Django 2.1.5 on 2019-02-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasingapi', '0008_auto_20190211_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='legalposition',
            name='clause_name',
        ),
        migrations.AddField(
            model_name='legalposition',
            name='clause_name',
            field=models.ManyToManyField(related_name='clause_description', to='leasingapi.Description'),
        ),
    ]
